### ISSUE TITLE
Beginner question: How can I run this plugin from the browser?

### ISSUE THREAD

**Issue by chipbite** [nopeslide/drawio_rtl_plugin#4] opened 2021-04-22 10:03 UTC
Is it possible, if I run the standard drawio app, diagrams net in the browser, e g:

https://app.diagrams.net/?splash=0&p=tags

How can I run this plugin, there?

If possible (?), I assume I need to point to some source by using menu `Extras > Plugins...` and selecting `Add...` and then `Custom...` and entering a URL - but to what? I looked in the repo, not sure.

Secondly, if that works, do I need to add the shapes library also?

Best regards!

**Comment by nopeslide** [comment] 2021-04-22 10:17
@chipbite
these plugins are bundled with drawio and mine is not.
draw.io does not allow loading of external plugins like mine.
This is not a bug of draw.io but a deliberate decision via their content security policy.
You either have to install the draw.io desktop version and load the plugin by hand or you can use the vscode draw.io integration and simply install this plugin via the marketplace.

the vscode integration does also not run inside a browser.
Sorry :/

If you have no other question, just close this this issue

**Comment by nopeslide** [comment] 2021-04-22 10:20
> I looked in the repo, not sure.
> 
> Secondly, if that works, do I need to add the shapes library also?

I always use local file, but you could try to specify the release bundle.
the plugin does not require anything else.
it just adds a palette (on the left side) with all shapes

**Closed** 2021-04-22 10:20 UTC
